products:
  - https://www.amazon.com/dp/B001ARYU58 # bowflex dumbbells
  - https://www.amazon.com/dp/B07373N7DR # nordictrack dumbbells
  - https://www.amazon.com/dp/B005ASREVK # stairaster dumbbells
  - https://www.amazon.com/dp/B08FC6MR62/ # PS5
