products:
  amazon:
    - https://www.amazon.com/dp/B08FC6MR62/ # PS5
    - https://www.amazon.com/Sonos-Arc-soundbar-subwoofer-Microphone-Free/dp/B087CD7H2G
    - https://www.amazon.com/gp/product/B08WC79S8P
web:
    - name: "Rally™ XC100 Single-sensing Power Meter"
      url: https://buy.garmin.com/en-US/US/p/658586/pn/010-02388-05
      selector: '.js__cta__buy'
