products:
  - https://www.amazon.com/gp/product/B006O0CLOS/
  - https://www.amazon.com/Bodylastics-Pcs-Resistance-Bands-Set/dp/B01H5K10VK # resistance bands level 6
  - https://www.amazon.com/dp/B001ARYU58 # bowflex dumbbells
  - https://www.amazon.com/dp/B07373N7DR # nordictrack dumbbells
  - https://www.amazon.com/dp/B005ASREVK # stairaster dumbbells
  - https://www.amazon.com/dp/B08FC6MR62/ # PS5
