products:
  - https://www.amazon.com/Bodylastics-Stackable-Resistance-Anti-Snap-Components/dp/B006NZZH18 # resistance bands level 1
  - https://www.amazon.com/Bodylastics-Stackable-Resistance-Anti-Snap-Components/dp/B006O09M4K # resistance bands level 2
  - https://www.amazon.com/Bodylastics-Military-Resistance-Anti-Snap-Components/dp/B012ZWS9DA # resistance bands level 3
  - https://www.amazon.com/Bodylastics-Pcs-Resistance-Bands-Set/dp/B006O0CLOS # resistance bands level 4
  - https://www.amazon.com/Bodylastics-Resistance-Anti-Snap-Exercise-components/dp/B006O0GDMO # resistance bands level 5
  - https://www.amazon.com/Bodylastics-Pcs-Resistance-Bands-Set/dp/B01H5K10VK # resistance bands level 6
  - https://www.amazon.com/dp/B001ARYU58 # bowflex dumbbells
  - https://www.amazon.com/dp/B07373N7DR # nordictrack dumbbells
  - https://www.amazon.com/dp/B005ASREVK # stairaster dumbbells
  - https://www.amazon.com/dp/B001ARYU58 # PS5
