products:
  - https://www.amazon.com/dp/B08FC6MR62/ # PS5
  - https://www.amazon.com/Xbox-X/dp/B08H75RTZ8/ # Xbox X
  - https://www.amazon.com/Sonos-Arc-soundbar-subwoofer-Microphone-Free/dp/B087CD7H2G
  - https://www.amazon.com/Sonos-Sub-Gen-Wireless-Subwoofer/dp/B087CCZH4Q/
