products:
  - name: resistance bands
    asin: B01H5K10VK
  - name: bowflex dumbbells
    asin: B001ARYU58
  - name: nordictrack dumbbells
    asin: B07373N7DR
  - name: core fitness dumbbells
    asin: B01J8S38LW
  - name: PS5
    asin: B08FC6MR62