products:
  - name: resistance bands
    asin: B01H5K10VK
  - name: bowflex dumbbells
    asin: B001ARYU58
  - name: nordictrack dumbbells
    asin: B07373N7DR
  - name: stairmaster dumbbells
    asin: B005ASREVK
  - name: PS5
    asin: B08FC6MR62
